// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kms"
	mock "github.com/stretchr/testify/mock"
)

// NewKMSAPI creates a new instance of KMSAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKMSAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *KMSAPI {
	mock := &KMSAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KMSAPI is an autogenerated mock type for the KMSAPI type
type KMSAPI struct {
	mock.Mock
}

type KMSAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *KMSAPI) EXPECT() *KMSAPI_Expecter {
	return &KMSAPI_Expecter{mock: &_m.Mock}
}

// GetPublicKey provides a mock function for the type KMSAPI
func (_mock *KMSAPI) GetPublicKey(context1 context.Context, getPublicKeyInput *kms.GetPublicKeyInput, fns ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, getPublicKeyInput, fns)
	} else {
		tmpRet = _mock.Called(context1, getPublicKeyInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPublicKey")
	}

	var r0 *kms.GetPublicKeyOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error)); ok {
		return returnFunc(context1, getPublicKeyInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) *kms.GetPublicKeyOutput); ok {
		r0 = returnFunc(context1, getPublicKeyInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.GetPublicKeyOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.GetPublicKeyInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(context1, getPublicKeyInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KMSAPI_GetPublicKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicKey'
type KMSAPI_GetPublicKey_Call struct {
	*mock.Call
}

// GetPublicKey is a helper method to define mock.On call
//   - context1 context.Context
//   - getPublicKeyInput *kms.GetPublicKeyInput
//   - fns ...func(*kms.Options)
func (_e *KMSAPI_Expecter) GetPublicKey(context1 any, getPublicKeyInput any, fns ...any) *KMSAPI_GetPublicKey_Call {
	return &KMSAPI_GetPublicKey_Call{Call: _e.mock.On("GetPublicKey",
		append([]any{context1, getPublicKeyInput}, fns...)...)}
}

func (_c *KMSAPI_GetPublicKey_Call) Run(run func(context1 context.Context, getPublicKeyInput *kms.GetPublicKeyInput, fns ...func(*kms.Options))) *KMSAPI_GetPublicKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.GetPublicKeyInput
		if args[1] != nil {
			arg1 = args[1].(*kms.GetPublicKeyInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KMSAPI_GetPublicKey_Call) Return(getPublicKeyOutput *kms.GetPublicKeyOutput, err error) *KMSAPI_GetPublicKey_Call {
	_c.Call.Return(getPublicKeyOutput, err)
	return _c
}

func (_c *KMSAPI_GetPublicKey_Call) RunAndReturn(run func(context1 context.Context, getPublicKeyInput *kms.GetPublicKeyInput, fns ...func(*kms.Options)) (*kms.GetPublicKeyOutput, error)) *KMSAPI_GetPublicKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type KMSAPI
func (_mock *KMSAPI) Sign(context1 context.Context, signInput *kms.SignInput, fns ...func(*kms.Options)) (*kms.SignOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, signInput, fns)
	} else {
		tmpRet = _mock.Called(context1, signInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 *kms.SignOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) (*kms.SignOutput, error)); ok {
		return returnFunc(context1, signInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) *kms.SignOutput); ok {
		r0 = returnFunc(context1, signInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kms.SignOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kms.SignInput, ...func(*kms.Options)) error); ok {
		r1 = returnFunc(context1, signInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KMSAPI_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type KMSAPI_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - context1 context.Context
//   - signInput *kms.SignInput
//   - fns ...func(*kms.Options)
func (_e *KMSAPI_Expecter) Sign(context1 any, signInput any, fns ...any) *KMSAPI_Sign_Call {
	return &KMSAPI_Sign_Call{Call: _e.mock.On("Sign",
		append([]any{context1, signInput}, fns...)...)}
}

func (_c *KMSAPI_Sign_Call) Run(run func(context1 context.Context, signInput *kms.SignInput, fns ...func(*kms.Options))) *KMSAPI_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kms.SignInput
		if args[1] != nil {
			arg1 = args[1].(*kms.SignInput)
		}
		var arg2 []func(*kms.Options)
		var variadicArgs []func(*kms.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*kms.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *KMSAPI_Sign_Call) Return(signOutput *kms.SignOutput, err error) *KMSAPI_Sign_Call {
	_c.Call.Return(signOutput, err)
	return _c
}

func (_c *KMSAPI_Sign_Call) RunAndReturn(run func(context1 context.Context, signInput *kms.SignInput, fns ...func(*kms.Options)) (*kms.SignOutput, error)) *KMSAPI_Sign_Call {
	_c.Call.Return(run)
	return _c
}
